name: Deploy on push
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v2

            -   name: Deploy
                run: make deploy
                env:
                    DOCKER_HOST: tcp://docker.ptheobald.co.uk:2375
