# This is a basic workflow to help you get started with Actions

name: CI-prod
on:
    schedule:
        -   cron: '30 4/6 * * *'

jobs:
    build:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v2

            -   name: Deploy
                run: make restart
                env:
                    DOCKER_HOST: tcp://docker.ptheobald.co.uk:2375
