name: Restart every 6 hours

on:
    schedule:
        -   cron: '30 4/6 * * *'

jobs:
    build:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v2

            -   name: Restart
                run: make restart
                env:
                    DOCKER_HOST: tcp://docker.ptheobald.co.uk:2375
